### ISSUE TITLE
Error when using logdna cli

### ISSUE THREAD

**Issue by pratikmallya** [logdna/logdna-cli#44]
Just trying to update gives this:

```
(default_venv) pmally@pmally0220mac ~/c/L/connect> logdna update
Checking for updates...
No update available. You have the latest version: 1.4.1
------------------------------------------------------------------
Uncaught Error: TypeError: Cannot read property 'statusCode' of undefined
    at Request.request.get [as _callback] (/usr/local/logdna/bin/lib/utils.js:175:55)
    at self.callback (/usr/local/logdna/bin/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Timeout._onTimeout (/usr/local/logdna/bin/node_modules/request/request.js:852:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
------------------------------------------------------------------
------------------------------------------------------------------
Uncaught Error: TypeError: Cannot read property 'statusCode' of undefined
    at Request.request.get [as _callback] (/usr/local/logdna/bin/lib/utils.js:175:55)
    at self.callback (/usr/local/logdna/bin/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.onRequestError (/usr/local/logdna/bin/node_modules/request/request.js:881:8)
    at ClientRequest.emit (events.js:203:15)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
------------------------------------------------------------------
(default_venv) pmally@pmally0220mac ~/c/L/connect>
```

**Comment by pratikmallya** [comment]
re-installing with `brew cask uninstall logdna-cli` then `brew cask install logdna-cli` fixed it
